[pytest]
testpaths =
    dse_v2/tests
    gem5_integration/tests
    model/generic_sim_backend/tests
norecursedirs =
    .git
    .omx
    .pytest_cache
    __pycache__
    gem5_integration/gem5
    runs
    tmp
    tmp*
