"""Reference workload adapters kept outside the domain-neutral core."""

from dse_v2.reference_workloads.dft import (
    DftCase,
    DftCoverageReport,
    DftKernelShape,
    DftPhase,
    SourceFact,
    build_dft_phase_graph,
    canonicalize_phase_id,
    dft_phase_reference_profile,
    domain_phase_summary_from_case,
    merge_source_facts,
    normalize_dft_case_from_facts,
    package_from_dft_case,
    stable_unknown_phase_id,
)
from dse_v2.reference_workloads.dft_qe import (
    DftQePwImporter,
    DftQePwStaticImporter,
    QeReferenceImporter,
    create_dft_qe_package,
    create_qe_reference_package,
    dft_qe_pw_profile,
    parse_qe_profile,
    parse_qe_pw_input,
    parse_qe_pw_log,
    qe_scf_reference_profile,
    register_dft_qe_importer,
    register_qe_reference_importer,
)

__all__ = [
    "DftCase",
    "DftCoverageReport",
    "DftKernelShape",
    "DftPhase",
    "DftQePwImporter",
    "DftQePwStaticImporter",
    "QeReferenceImporter",
    "SourceFact",
    "build_dft_phase_graph",
    "canonicalize_phase_id",
    "create_dft_qe_package",
    "create_qe_reference_package",
    "dft_phase_reference_profile",
    "dft_qe_pw_profile",
    "domain_phase_summary_from_case",
    "merge_source_facts",
    "normalize_dft_case_from_facts",
    "package_from_dft_case",
    "parse_qe_profile",
    "parse_qe_pw_input",
    "parse_qe_pw_log",
    "qe_scf_reference_profile",
    "register_dft_qe_importer",
    "register_qe_reference_importer",
    "stable_unknown_phase_id",
]
