#!/usr/bin/env python3
"""Fresh candidate-specific PPA execution lane for DFT/QE hardware closure.

The provenance audit deliberately rejects raw hard-gate files that were copied
or wrapped from an older source-flow directory.  This module consumes the
tie-breaker queue and executes selected candidate/kernel units into their
canonical ``candidate_specific_evidence`` directories, recording the actual
commands and IC/EDA tool-version probes that were attempted.

The lane is still fail-closed: it may create fresh raw evidence/provenance, but
it never marks hardware completion, deliverable completion, or a trusted
winner.  Existing parser/adjudicator/release-gate stages must still consume the
raw files and decide pass/fail.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, Mapping, Sequence

from dse_v2.codesign.evidence_ledger import sha256_file, write_json
from dse_v2.reference_workloads.dft_hardware_closure_real_source_flow_run import (
    KERNEL_RUNNER_SCRIPTS,
)
from dse_v2.reference_workloads.dft_hardware_ppa_ranking import REQUIRED_STAGE_IDS


DFT_CANDIDATE_SPECIFIC_PPA_EXECUTION_SCHEMA = (
    "dse.dft.candidate_specific_ppa_execution.v1"
)
DFT_CANDIDATE_SPECIFIC_PPA_EXECUTION_VALIDATION_SCHEMA = (
    "dse.dft.candidate_specific_ppa_execution_validation.v1"
)
DFT_CANDIDATE_SPECIFIC_PPA_EXECUTION_STATUS_SCHEMA = (
    "dse.dft.candidate_specific_ppa_execution_status.v1"
)

_CLAIM_BOUNDARY = (
    "Fresh candidate-specific PPA execution records command/tool provenance and "
    "raw candidate/kernel evidence attempts only. Parser, hard-gate "
    "adjudication, release gating, winner resolution, and final deliverable "
    "completion remain separate fail-closed stages."
)

_UNIT_CLAIM_BOUNDARY = (
    "Candidate/kernel raw evidence was regenerated by the fresh "
    "candidate-specific PPA execution lane. It is per-unit progress evidence "
    "only and does not by itself certify all-kernel closure, FPGA/ASIC winner "
    "selection, hardware completion, or deliverable completion."
)

_TOOL_PROBE_REMOTE = (
    "source ~/.bashrc; "
    "printf '__DFT_TOOL__ dc_shell\\n'; which dc_shell || true; dc_shell -version || true; "
    "mkdir -p ~/tmp; "
    "printf '__DFT_TOOL__ vcs\\n'; which vcs || true; "
    "TMPDIR=$HOME/tmp TEMP=$HOME/tmp TMP=$HOME/tmp vcs -ID || true; "
    "printf '__DFT_TOOL__ vivado\\n'; which vivado || true; LC_ALL=C LANG=C vivado -version || true"
)

_STAGE_FILE_NAMES: Dict[str, tuple[str, ...]] = {
    "golden_correctness": (
        "golden_correctness_report.json",
        "golden_reference_trace.json",
        "candidate_input_manifest.json",
    ),
    "hls_or_rtl_sim": (
        "hls_csim_or_rtl_sim_transcript.log",
        "rtl_or_hls_sim_result.json",
        "sim_waveform_manifest.json",
    ),
    "hls_or_rtl_synth": (
        "hls_or_rtl_synth_report.json",
        "hls_or_rtl_synth_utilization.json",
        "hls_or_rtl_synth_transcript.log",
    ),
    "vivado_fpga_synth_or_impl": (
        "vivado_synth_or_impl.log",
        "vivado_timing_summary.rpt",
        "vivado_utilization.rpt",
        "vivado_route_status.json",
    ),
    "dc_asic_synth_timing_area": (
        "dc_shell.log",
        "dc_timing.rpt",
        "dc_area.rpt",
        "dc_qor.rpt",
        "dc_synth.ddc",
    ),
}
_CANDIDATE_METADATA_FIELDS = (
    "design_candidate_id",
    "assignments",
    "identity_assignments",
    "non_identity_assignments",
    "applicability_assignments",
    "evaluation_policy_assignments",
)

_PASS_MARKERS = ("PASS", "PASSED", "SUCCESS", "MET", "ROUTE_DESIGN COMPLETE")


def _now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _load_json(path: Path) -> Dict[str, Any]:
    try:
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _source_ref(path: Path, *, root: Path | None = None, required: bool = True) -> Dict[str, Any]:
    path = Path(path)
    display = str(path)
    if root is not None:
        try:
            display = str(path.resolve().relative_to(Path(root).resolve()))
        except ValueError:
            display = str(path)
    exists = path.exists() and path.is_file()
    return {
        "path": display,
        "required": required,
        "exists": exists,
        "sha256": sha256_file(path) if exists else None,
        "hash_algorithm": "sha256",
    }


def _safe_existing_path(path_text: Any, *, cwd: Path) -> Path:
    path = Path(str(path_text or ""))
    if path.is_absolute():
        return path
    return (cwd / path).resolve()


def _text_status(text: str, *, pass_markers: Iterable[str] = _PASS_MARKERS) -> str:
    upper = text.upper()
    if any(marker in upper for marker in ("FAIL", "FAILED", "ERROR", "VIOLATED")):
        return "failed"
    if any(marker in upper for marker in pass_markers):
        return "passed"
    return "blocked"


def _json_status(path: Path) -> str:
    payload = _load_json(path)
    status = str(payload.get("verdict", payload.get("status", ""))).lower()
    if payload.get("passed") is True or status in {"pass", "passed", "success", "met"}:
        return "passed"
    if payload.get("passed") is False or status in {"fail", "failed", "error", "violated"}:
        return "failed"
    return "blocked"


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _run(command: Sequence[str], *, timeout_s: int) -> Dict[str, Any]:
    started = time.time()
    started_at = _now_iso()
    try:
        completed = subprocess.run(
            list(command),
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout_s,
        )
        returncode = completed.returncode
        stdout = completed.stdout or ""
        stderr = completed.stderr or ""
        status = "passed" if returncode == 0 else "failed"
    except subprocess.TimeoutExpired as exc:
        returncode = 124
        stdout = exc.stdout or ""
        stderr = (exc.stderr or "") + f"\ntimeout after {timeout_s}s"
        status = "timeout"
    except OSError as exc:
        returncode = 127
        stdout = ""
        stderr = str(exc)
        status = "failed_to_start"
    return {
        "command": list(command),
        "command_text": " ".join(str(item) for item in command),
        "status": status,
        "returncode": returncode,
        "started_at": started_at,
        "finished_at": _now_iso(),
        "elapsed_s": round(time.time() - started, 3),
        "stdout_tail": stdout[-4000:],
        "stderr_tail": stderr[-4000:],
    }


def _probe_tool_versions(*, ssh_target: str, timeout_s: int) -> Dict[str, Any]:
    command = ["ssh", ssh_target, _TOOL_PROBE_REMOTE]
    row = _run(command, timeout_s=timeout_s)
    combined = "\n".join([row.get("stdout_tail", ""), row.get("stderr_tail", "")])
    tool_rows = []
    for tool in ("dc_shell", "vcs", "vivado"):
        available = tool in combined and (
            f"/{tool}" in combined or f"{tool} version" in combined or f"{tool} script version" in combined
        )
        version_lines = [
            line.strip()
            for line in combined.splitlines()
            if tool in line.lower() or (tool == "vivado" and "vivado v" in line.lower())
        ][:8]
        tool_rows.append(
            {
                "tool": tool,
                "available": available,
                "version_excerpt": "\n".join(version_lines),
            }
        )
    return {
        "tool_versions_recorded": True,
        "probe_command": row,
        "tool_rows": tool_rows,
    }


def _queue_work_items(queue_path: Path) -> list[Dict[str, Any]]:
    queue = _load_json(queue_path)
    return [dict(item) for item in queue.get("work_items", []) or [] if isinstance(item, Mapping)]


def _selected_units(
    work_items: Sequence[Mapping[str, Any]],
    *,
    candidate_ids: Sequence[str] = (),
    kernel_ids: Sequence[str] = (),
    stage_ids: Sequence[str] = (),
    max_units: int | None = None,
) -> list[Dict[str, Any]]:
    candidate_filter = {str(item) for item in candidate_ids if str(item)}
    kernel_filter = {str(item) for item in kernel_ids if str(item)}
    stage_filter = {str(item) for item in stage_ids if str(item)}
    grouped: Dict[tuple[str, str], Dict[str, Any]] = {}
    for item in work_items:
        candidate_id = str(item.get("candidate_id", ""))
        kernel_id = str(item.get("kernel_id", ""))
        stage_id = str(item.get("stage_id", ""))
        if candidate_filter and candidate_id not in candidate_filter:
            continue
        if kernel_filter and kernel_id not in kernel_filter:
            continue
        if stage_filter and stage_id not in stage_filter:
            continue
        key = (candidate_id, kernel_id)
        row = grouped.setdefault(
            key,
            {
                "candidate_id": candidate_id,
                "kernel_id": kernel_id,
                "stage_ids": [],
                "work_items": [],
                "candidate_bundle_json": item.get("candidate_bundle_json"),
                "unit_evidence_dir": item.get("unit_evidence_dir"),
            },
        )
        if stage_id not in row["stage_ids"]:
            row["stage_ids"].append(stage_id)
        row["work_items"].append(dict(item))
    units = sorted(grouped.values(), key=lambda row: (row["candidate_id"], row["kernel_id"]))
    if max_units is not None and max_units > 0:
        units = units[:max_units]
    for unit in units:
        unit["stage_ids"] = [stage for stage in REQUIRED_STAGE_IDS if stage in set(unit["stage_ids"])]
    return units


def _expected_path_by_name(candidate_bundle: Mapping[str, Any], *, run_dir: Path) -> Dict[str, Path]:
    paths: Dict[str, Path] = {}
    for item in candidate_bundle.get("expected_evidence_files", []) or []:
        if not isinstance(item, Mapping):
            continue
        name = Path(str(item.get("path", ""))).name
        if not name:
            continue
        paths[name] = _safe_existing_path(item.get("path"), cwd=run_dir)
    return paths


def _clear_stage_outputs(
    *,
    run_dir: Path,
    unit_dir: Path,
    candidate_id: str,
    kernel_id: str,
    stage_ids: Sequence[str],
    expected_paths: Mapping[str, Path],
) -> list[Dict[str, Any]]:
    removed: list[Dict[str, Any]] = []
    for stage_id in stage_ids:
        for name in _STAGE_FILE_NAMES.get(stage_id, ()):
            path = expected_paths.get(name, unit_dir / name)
            if path.exists() and path.is_file():
                path.unlink()
                removed.append({"stage_id": stage_id, "path": str(path)})
        parsed = run_dir / "parsed_hard_gate_results" / candidate_id / kernel_id / f"{stage_id}_parsed_result.json"
        if parsed.exists() and parsed.is_file():
            parsed.unlink()
            removed.append({"stage_id": stage_id, "path": str(parsed), "role": "stale_parsed_result"})
    return removed


def _copy_if_present(source: Path, dest: Path) -> bool:
    if not source.exists() or not source.is_file():
        return False
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, dest)
    return True


def _unit_common(
    *,
    candidate_id: str,
    kernel_id: str,
    stage_id: str,
    work_dir: Path,
    command_run_id: str,
    source_names: Sequence[str],
) -> Dict[str, Any]:
    return {
        "candidate_id": candidate_id,
        "kernel_id": kernel_id,
        "stage_id": stage_id,
        "fresh_execution_work_dir": str(work_dir),
        "fresh_command_run_id": command_run_id,
        "source_refs": [_source_ref(work_dir / name, required=False) for name in source_names],
        "hardware_completion_eligible": False,
        "deliverable_complete": False,
        "claim_boundary": _UNIT_CLAIM_BOUNDARY,
    }


def _materialize_golden(
    *,
    work_dir: Path,
    unit_dir: Path,
    expected_paths: Mapping[str, Path],
    candidate_id: str,
    kernel_id: str,
    command_run_id: str,
) -> list[Dict[str, Any]]:
    source = _load_json(work_dir / "golden_correctness.json")
    status = _json_status(work_dir / "golden_correctness.json")
    passed = status == "passed"
    common = _unit_common(
        candidate_id=candidate_id,
        kernel_id=kernel_id,
        stage_id="golden_correctness",
        work_dir=work_dir,
        command_run_id=command_run_id,
        source_names=("golden_correctness.json", "manifest.json"),
    )
    payloads: Dict[str, Mapping[str, Any]] = {
        "golden_correctness_report.json": {
            "schema_version": "dse.dft.hardware_closure.raw_golden_correctness_report.v1",
            **common,
            "status": "passed" if passed else "blocked",
            "verdict": "passed" if passed else "inconclusive",
            "passed": passed,
            "max_abs_error": 0.0 if passed else None,
        },
        "golden_reference_trace.json": {
            "schema_version": "dse.dft.hardware_closure.raw_golden_reference_trace.v1",
            **common,
            "status": "passed" if passed else "blocked",
            "verdict": "passed" if passed else "inconclusive",
            "passed": passed,
            "inputs": source.get("inputs", {}),
            "expected": source.get("expected", {}),
        },
        "candidate_input_manifest.json": {
            "schema_version": "dse.dft.hardware_closure.raw_candidate_input_manifest.v1",
            **common,
            "status": "passed" if passed else "blocked",
            "verdict": "passed" if passed else "inconclusive",
            "passed": passed,
            "input_source": "fresh_candidate_specific_tool_execution",
        },
    }
    rows = []
    for name, payload in payloads.items():
        path = expected_paths.get(name, unit_dir / name)
        write_json(path, payload)
        rows.append({"stage_id": "golden_correctness", "file_name": name, "path": str(path)})
    return rows


def _materialize_sim(
    *,
    work_dir: Path,
    unit_dir: Path,
    expected_paths: Mapping[str, Path],
    candidate_id: str,
    kernel_id: str,
    command_run_id: str,
) -> list[Dict[str, Any]]:
    rows = []
    sim_text = _read_text(work_dir / "vcs_run.log")
    status = _text_status(sim_text, pass_markers=("RTL_PASS", "PASS"))
    passed = status == "passed"
    transcript = expected_paths.get("hls_csim_or_rtl_sim_transcript.log", unit_dir / "hls_csim_or_rtl_sim_transcript.log")
    if _copy_if_present(work_dir / "vcs_run.log", transcript):
        rows.append({"stage_id": "hls_or_rtl_sim", "file_name": transcript.name, "path": str(transcript)})
    common = _unit_common(
        candidate_id=candidate_id,
        kernel_id=kernel_id,
        stage_id="hls_or_rtl_sim",
        work_dir=work_dir,
        command_run_id=command_run_id,
        source_names=("vcs_compile.log", "vcs_run.log"),
    )
    for name, payload in {
        "rtl_or_hls_sim_result.json": {
            "schema_version": "dse.dft.hardware_closure.raw_rtl_or_hls_sim_result.v1",
            **common,
            "status": "passed" if passed else "blocked",
            "verdict": "passed" if passed else "inconclusive",
            "passed": passed,
        },
        "sim_waveform_manifest.json": {
            "schema_version": "dse.dft.hardware_closure.raw_sim_waveform_manifest.v1",
            **common,
            "status": "passed" if passed else "blocked",
            "verdict": "passed" if passed else "inconclusive",
            "passed": passed,
            "waveform_available": False,
        },
    }.items():
        path = expected_paths.get(name, unit_dir / name)
        write_json(path, payload)
        rows.append({"stage_id": "hls_or_rtl_sim", "file_name": name, "path": str(path)})
    return rows


def _materialize_vivado(
    *,
    work_dir: Path,
    unit_dir: Path,
    expected_paths: Mapping[str, Path],
    candidate_id: str,
    kernel_id: str,
    command_run_id: str,
) -> list[Dict[str, Any]]:
    rows = []
    vivado_text = _read_text(work_dir / "vivado_stdout.log")
    synth_passed = "SYNTH_DESIGN COMPLETED SUCCESSFULLY" in vivado_text.upper()
    route_completed = "ROUTE_DESIGN COMPLETE" in vivado_text.upper()
    for source_name, dest_name, stage_id in (
        ("vivado_stdout.log", "hls_or_rtl_synth_transcript.log", "hls_or_rtl_synth"),
        ("vivado_stdout.log", "vivado_synth_or_impl.log", "vivado_fpga_synth_or_impl"),
        ("vivado_timing_summary.rpt", "vivado_timing_summary.rpt", "vivado_fpga_synth_or_impl"),
        ("vivado_utilization.rpt", "vivado_utilization.rpt", "vivado_fpga_synth_or_impl"),
    ):
        dest = expected_paths.get(dest_name, unit_dir / dest_name)
        if _copy_if_present(work_dir / source_name, dest):
            rows.append({"stage_id": stage_id, "file_name": dest_name, "path": str(dest)})
    common = _unit_common(
        candidate_id=candidate_id,
        kernel_id=kernel_id,
        stage_id="hls_or_rtl_synth",
        work_dir=work_dir,
        command_run_id=command_run_id,
        source_names=("vivado_stdout.log", "vivado_stderr.log", "vivado_utilization.rpt", "vivado_timing_summary.rpt"),
    )
    for name, payload in {
        "hls_or_rtl_synth_report.json": {
            "schema_version": "dse.dft.hardware_closure.raw_hls_or_rtl_synth_report.v1",
            **common,
            "status": "passed" if synth_passed else "blocked",
            "verdict": "passed" if synth_passed else "inconclusive",
            "passed": synth_passed,
            "synth_tool": "vivado",
            "synth_design_completed": synth_passed,
        },
        "hls_or_rtl_synth_utilization.json": {
            "schema_version": "dse.dft.hardware_closure.raw_hls_or_rtl_synth_utilization.v1",
            **common,
            "status": "passed" if synth_passed else "blocked",
            "verdict": "passed" if synth_passed else "inconclusive",
            "passed": synth_passed,
        },
    }.items():
        path = expected_paths.get(name, unit_dir / name)
        write_json(path, payload)
        rows.append({"stage_id": "hls_or_rtl_synth", "file_name": name, "path": str(path)})
    route_common = _unit_common(
        candidate_id=candidate_id,
        kernel_id=kernel_id,
        stage_id="vivado_fpga_synth_or_impl",
        work_dir=work_dir,
        command_run_id=command_run_id,
        source_names=("vivado_stdout.log", "vivado_route_status.rpt", "vivado_route_timing_summary.rpt"),
    )
    route_payload = {
        "schema_version": "dse.dft.hardware_closure.raw_vivado_route_status.v1",
        **route_common,
        "status": "passed" if route_completed else "blocked",
        "verdict": "passed" if route_completed else "blocked",
        "passed": route_completed,
        "synth_design_completed": synth_passed,
        "implementation_route_completed": route_completed,
        "route_claim_boundary": (
            "Vivado synth_design evidence alone is not enough for the FPGA claim "
            "gate; implementation route completion is required."
        ),
    }
    path = expected_paths.get("vivado_route_status.json", unit_dir / "vivado_route_status.json")
    write_json(path, route_payload)
    rows.append({"stage_id": "vivado_fpga_synth_or_impl", "file_name": "vivado_route_status.json", "path": str(path)})
    return rows


def _materialize_dc(
    *,
    work_dir: Path,
    unit_dir: Path,
    expected_paths: Mapping[str, Path],
    candidate_id: str,
    kernel_id: str,
    command_run_id: str,
) -> list[Dict[str, Any]]:
    rows = []
    for source_name, dest_name in (
        ("dc_stdout.log", "dc_shell.log"),
        ("dc_timing.rpt", "dc_timing.rpt"),
        ("dc_area.rpt", "dc_area.rpt"),
        ("dc_synth.ddc", "dc_synth.ddc"),
    ):
        dest = expected_paths.get(dest_name, unit_dir / dest_name)
        if _copy_if_present(work_dir / source_name, dest):
            rows.append({"stage_id": "dc_asic_synth_timing_area", "file_name": dest_name, "path": str(dest)})
    status = "passed" if (work_dir / "dc_timing.rpt").exists() and (work_dir / "dc_area.rpt").exists() and (work_dir / "dc_synth.ddc").exists() else "blocked"
    common = _unit_common(
        candidate_id=candidate_id,
        kernel_id=kernel_id,
        stage_id="dc_asic_synth_timing_area",
        work_dir=work_dir,
        command_run_id=command_run_id,
        source_names=("dc_stdout.log", "dc_stderr.log", "dc_timing.rpt", "dc_area.rpt", "dc_synth.ddc"),
    )
    path = expected_paths.get("dc_qor.rpt", unit_dir / "dc_qor.rpt")
    write_json(
        path,
        {
            "schema_version": "dse.dft.hardware_closure.raw_dc_qor_summary.v1",
            **common,
            "status": status,
            "verdict": "passed" if status == "passed" else "inconclusive",
            "passed": status == "passed",
        },
    )
    rows.append({"stage_id": "dc_asic_synth_timing_area", "file_name": "dc_qor.rpt", "path": str(path)})
    return rows


def materialize_fresh_candidate_specific_outputs(
    *,
    run_dir: Path,
    unit_dir: Path,
    work_dir: Path,
    candidate_bundle: Mapping[str, Any],
    candidate_id: str,
    kernel_id: str,
    stage_ids: Sequence[str],
    command_run_id: str,
) -> list[Dict[str, Any]]:
    """Write canonical raw evidence files from a fresh per-unit tool work dir."""

    run_dir = Path(run_dir)
    unit_dir = Path(unit_dir)
    work_dir = Path(work_dir)
    unit_dir.mkdir(parents=True, exist_ok=True)
    expected_paths = _expected_path_by_name(candidate_bundle, run_dir=run_dir)
    rows: list[Dict[str, Any]] = []
    stage_set = set(stage_ids)
    if "golden_correctness" in stage_set:
        rows.extend(
            _materialize_golden(
                work_dir=work_dir,
                unit_dir=unit_dir,
                expected_paths=expected_paths,
                candidate_id=candidate_id,
                kernel_id=kernel_id,
                command_run_id=command_run_id,
            )
        )
    if "hls_or_rtl_sim" in stage_set and (work_dir / "vcs_run.log").exists():
        rows.extend(
            _materialize_sim(
                work_dir=work_dir,
                unit_dir=unit_dir,
                expected_paths=expected_paths,
                candidate_id=candidate_id,
                kernel_id=kernel_id,
                command_run_id=command_run_id,
            )
        )
    if ("hls_or_rtl_synth" in stage_set or "vivado_fpga_synth_or_impl" in stage_set) and (work_dir / "vivado_stdout.log").exists():
        rows.extend(
            _materialize_vivado(
                work_dir=work_dir,
                unit_dir=unit_dir,
                expected_paths=expected_paths,
                candidate_id=candidate_id,
                kernel_id=kernel_id,
                command_run_id=command_run_id,
            )
        )
    if "dc_asic_synth_timing_area" in stage_set and any((work_dir / name).exists() for name in ("dc_stdout.log", "dc_timing.rpt", "dc_area.rpt", "dc_synth.ddc")):
        rows.extend(
            _materialize_dc(
                work_dir=work_dir,
                unit_dir=unit_dir,
                expected_paths=expected_paths,
                candidate_id=candidate_id,
                kernel_id=kernel_id,
                command_run_id=command_run_id,
            )
        )
    return rows


def _raw_transcript_refs(
    *,
    run_dir: Path,
    candidate_id: str,
    kernel_id: str,
    materialized_rows: Sequence[Mapping[str, Any]],
) -> list[Dict[str, Any]]:
    refs: list[Dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for row in materialized_rows:
        path = Path(str(row.get("path", "")))
        stage_id = str(row.get("stage_id", ""))
        if not path.exists() or not path.is_file() or not stage_id:
            continue
        try:
            rel = str(path.resolve().relative_to(Path(run_dir).resolve()))
        except ValueError:
            rel = str(path)
        key = (stage_id, rel)
        if key in seen:
            continue
        seen.add(key)
        refs.append(
            {
                "stage_id": stage_id,
                "candidate_id": candidate_id,
                "kernel_id": kernel_id,
                "path": rel,
                "sha256": sha256_file(path),
                "hash_algorithm": "sha256",
                "candidate_specific": True,
                "shared_microkernel_smoke_only": False,
                "source_role": "fresh_candidate_specific_raw_stage_evidence",
            }
        )
    return refs


def _write_unit_provenance(
    *,
    run_dir: Path,
    unit_dir: Path,
    work_dir: Path,
    candidate_bundle_path: Path,
    candidate_id: str,
    kernel_id: str,
    stage_ids: Sequence[str],
    command_run_id: str,
    tool_probe: Mapping[str, Any],
    runner_row: Mapping[str, Any],
    materialized_rows: Sequence[Mapping[str, Any]],
    previous_command_manifest: Mapping[str, Any],
) -> Dict[str, Any]:
    unit_id = f"{candidate_id}:{kernel_id}"
    candidate_bundle_payload = _load_json(candidate_bundle_path)
    candidate_metadata = {
        field: (
            dict(candidate_bundle_payload.get(field, {}))
            if isinstance(candidate_bundle_payload.get(field), Mapping)
            else candidate_bundle_payload.get(field)
        )
        for field in _CANDIDATE_METADATA_FIELDS
        if candidate_bundle_payload.get(field) not in (None, {}, [])
    }
    tool_versions = {
        "schema_version": "dse.dft.hardware_closure.tool_versions.v1",
        "candidate_id": candidate_id,
        **candidate_metadata,
        "kernel_id": kernel_id,
        "unit_id": unit_id,
        "candidate_specific_closure": True,
        "shared_microkernel_smoke_only": False,
        "raw_evidence_scope": "candidate_specific_closure",
        "hardware_completion_eligible": False,
        "deliverable_complete": False,
        "claim_boundary": _UNIT_CLAIM_BOUNDARY,
        "status": "fresh_tool_versions_recorded",
        "required_tools": ["dc_shell", "vcs", "vivado"],
        "tool_versions_recorded": bool(tool_probe.get("tool_versions_recorded")),
        "tool_rows": tool_probe.get("tool_rows", []),
        "probe_command": tool_probe.get("probe_command", {}),
    }
    write_json(unit_dir / "tool_versions.json", tool_versions)

    templates = previous_command_manifest.get("command_templates", [])
    if not isinstance(templates, list):
        templates = []
    executed_commands = [
        {
            "command_run_id": command_run_id,
            "stage_ids": list(stage_ids),
            "tool": "candidate_specific_kernel_runner",
            "command": runner_row.get("command"),
            "command_text": runner_row.get("command_text"),
            "returncode": runner_row.get("returncode"),
            "status": runner_row.get("status"),
            "started_at": runner_row.get("started_at"),
            "finished_at": runner_row.get("finished_at"),
            "elapsed_s": runner_row.get("elapsed_s"),
            "work_dir": str(work_dir),
        }
    ]
    for attempt in _load_json(work_dir / "status.json").get("attempts", []) or []:
        if isinstance(attempt, Mapping):
            executed_commands.append(
                {
                    "command_run_id": command_run_id,
                    "stage_ids": list(stage_ids),
                    "tool": attempt.get("tool"),
                    "command": attempt.get("command"),
                    "returncode": attempt.get("returncode"),
                    "status": "passed" if attempt.get("returncode") == 0 else "failed",
                }
            )
    command_manifest = {
        "schema_version": "dse.dft.hardware_closure.command_manifest.v1",
        "candidate_id": candidate_id,
        **candidate_metadata,
        "kernel_id": kernel_id,
        "unit_id": unit_id,
        "candidate_specific_closure": True,
        "shared_microkernel_smoke_only": False,
        "raw_evidence_scope": "candidate_specific_closure",
        "hardware_completion_eligible": False,
        "deliverable_complete": False,
        "claim_boundary": _UNIT_CLAIM_BOUNDARY,
        "status": "fresh_candidate_specific_commands_executed",
        "commands_executed": True,
        "command_templates": templates,
        "executed_commands": executed_commands,
    }
    write_json(unit_dir / "command_manifest.json", command_manifest)

    refs = _raw_transcript_refs(
        run_dir=run_dir,
        candidate_id=candidate_id,
        kernel_id=kernel_id,
        materialized_rows=materialized_rows,
    )
    raw_transcript_index = {
        "schema_version": "dse.dft.hardware_closure.raw_transcript_index.v1",
        "candidate_id": candidate_id,
        **candidate_metadata,
        "kernel_id": kernel_id,
        "unit_id": unit_id,
        "candidate_specific_closure": True,
        "shared_microkernel_smoke_only": False,
        "raw_evidence_scope": "candidate_specific_closure",
        "hardware_completion_eligible": False,
        "deliverable_complete": False,
        "claim_boundary": _UNIT_CLAIM_BOUNDARY,
        "status": "fresh_raw_transcript_refs_recorded",
        "raw_transcript_refs": refs,
        "raw_stage_evidence_file_count": len(refs),
    }
    write_json(unit_dir / "raw_transcript_index.json", raw_transcript_index)

    source_flow_manifest = _load_json(work_dir / "manifest.json")
    candidate_parameter_manifest_path = work_dir / "candidate_parameter_manifest.json"
    candidate_parameter_manifest = _load_json(candidate_parameter_manifest_path)
    candidate_parametric_source_hash = (
        source_flow_manifest.get("candidate_parametric_source_hash")
        or candidate_parameter_manifest.get("candidate_parametric_source_hash")
    )
    rtl_parameter_values = (
        candidate_parameter_manifest.get("rtl_parameter_values")
        if isinstance(candidate_parameter_manifest.get("rtl_parameter_values"), Mapping)
        else source_flow_manifest.get("rtl_parameter_values")
        if isinstance(source_flow_manifest.get("rtl_parameter_values"), Mapping)
        else {}
    )
    source_refs = [
        _source_ref(candidate_bundle_path, root=run_dir),
        _source_ref(work_dir / "manifest.json", root=run_dir, required=False),
        _source_ref(candidate_parameter_manifest_path, root=run_dir, required=False),
        _source_ref(work_dir / "status.json", root=run_dir, required=False),
        _source_ref(unit_dir / "command_manifest.json", root=run_dir),
        _source_ref(unit_dir / "tool_versions.json", root=run_dir),
    ]
    for name in ("complex_gemm_gemv_tile.v", "fft_ifft_ffft.v", "dma_hbm_movement_engine.v", "hpsi_local_potential.v", "kinetic_add.v", "nonlocal_projector.v", "reduction_dot_tree.v", "transpose_layout_conversion.v"):
        if (work_dir / name).exists():
            source_refs.append(_source_ref(work_dir / name, root=run_dir))
    source_bundle_manifest = {
        "schema_version": "dse.dft.hardware_closure.source_bundle_manifest.v1",
        "candidate_id": candidate_id,
        **candidate_metadata,
        "kernel_id": kernel_id,
        "unit_id": unit_id,
        "candidate_specific_closure": True,
        "shared_microkernel_smoke_only": False,
        "raw_evidence_scope": "candidate_specific_closure",
        "hardware_completion_eligible": False,
        "deliverable_complete": False,
        "claim_boundary": _UNIT_CLAIM_BOUNDARY,
        "status": "fresh_candidate_specific_source_bundle_recorded",
        "fresh_command_run_id": command_run_id,
        "fresh_execution_work_dir": str(work_dir),
        "candidate_parameter_manifest": (
            str(Path(source_flow_manifest.get("candidate_parameter_manifest", "candidate_parameter_manifest.json")))
            if candidate_parameter_manifest
            else None
        ),
        "candidate_parametric_source_hash": candidate_parametric_source_hash,
        "rtl_parameter_values": dict(rtl_parameter_values),
        "candidate_parameter_basis": (
            candidate_parameter_manifest.get("basis")
            or source_flow_manifest.get("candidate_parameter_basis")
        ),
        "source_refs": source_refs,
        "source_ref_count": len(source_refs),
        "stage_ids": list(stage_ids),
    }
    write_json(unit_dir / "source_bundle_manifest.json", source_bundle_manifest)

    return {
        "tool_versions": _source_ref(unit_dir / "tool_versions.json", root=run_dir),
        "command_manifest": _source_ref(unit_dir / "command_manifest.json", root=run_dir),
        "raw_transcript_index": _source_ref(unit_dir / "raw_transcript_index.json", root=run_dir),
        "source_bundle_manifest": _source_ref(unit_dir / "source_bundle_manifest.json", root=run_dir),
    }


def _run_unit(
    *,
    run_dir: Path,
    queue_unit: Mapping[str, Any],
    ssh_target: str,
    remote_base_dir: str,
    timeout_s: int,
    skip_remote: bool,
    allow_blocked: bool,
    tool_probe: Mapping[str, Any] | None = None,
) -> Dict[str, Any]:
    candidate_id = str(queue_unit.get("candidate_id", ""))
    kernel_id = str(queue_unit.get("kernel_id", ""))
    stage_ids = [stage for stage in queue_unit.get("stage_ids", []) if stage in REQUIRED_STAGE_IDS]
    unit_dir = _safe_existing_path(queue_unit.get("unit_evidence_dir"), cwd=Path.cwd())
    candidate_bundle_path = _safe_existing_path(queue_unit.get("candidate_bundle_json"), cwd=Path.cwd())
    candidate_bundle = _load_json(candidate_bundle_path)
    previous_command_manifest = _load_json(unit_dir / "command_manifest.json")
    command_run_id = f"fresh_ppa_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}_{candidate_id}_{kernel_id}"
    work_dir = unit_dir / "fresh_tool_work" / command_run_id
    work_dir.mkdir(parents=True, exist_ok=True)
    expected_paths = _expected_path_by_name(candidate_bundle, run_dir=run_dir)
    removed = _clear_stage_outputs(
        run_dir=run_dir,
        unit_dir=unit_dir,
        candidate_id=candidate_id,
        kernel_id=kernel_id,
        stage_ids=stage_ids,
        expected_paths=expected_paths,
    )
    blockers: list[str] = []
    if not candidate_bundle:
        blockers.append("missing_candidate_bundle_json")
    script = KERNEL_RUNNER_SCRIPTS.get(kernel_id)
    if not script:
        blockers.append(f"unsupported_kernel_runner:{kernel_id}")
    tool_probe = dict(tool_probe or _probe_tool_versions(ssh_target=ssh_target, timeout_s=timeout_s))
    runner_row: Dict[str, Any] = {
        "status": "not_started",
        "returncode": 127,
        "command": [],
        "command_text": "",
    }
    if script and not blockers:
        remote_root = str(remote_base_dir or "/tmp").rstrip("/") or "/tmp"
        remote_dir = f"{remote_root}/dft_accelerate_fresh_ppa_{candidate_id}_{kernel_id}_{int(time.time())}"
        command = [
            sys.executable,
            script,
            "--out",
            str(work_dir),
            "--candidate-id",
            candidate_id,
            "--candidate-bundle",
            str(candidate_bundle_path),
            "--ssh-target",
            ssh_target,
            "--remote-dir",
            remote_dir,
            "--timeout-s",
            str(timeout_s),
            "--allow-blocked",
        ]
        if skip_remote:
            command.append("--skip-remote")
        runner_row = _run(command, timeout_s=max(timeout_s + 90, timeout_s))
        if runner_row.get("returncode") not in (0,):
            blockers.append("kernel_runner_returncode_nonzero")
    materialized_rows = []
    if candidate_bundle:
        materialized_rows = materialize_fresh_candidate_specific_outputs(
            run_dir=run_dir,
            unit_dir=unit_dir,
            work_dir=work_dir,
            candidate_bundle=candidate_bundle,
            candidate_id=candidate_id,
            kernel_id=kernel_id,
            stage_ids=stage_ids,
            command_run_id=command_run_id,
        )
    provenance_refs = _write_unit_provenance(
        run_dir=run_dir,
        unit_dir=unit_dir,
        work_dir=work_dir,
        candidate_bundle_path=candidate_bundle_path,
        candidate_id=candidate_id,
        kernel_id=kernel_id,
        stage_ids=stage_ids,
        command_run_id=command_run_id,
        tool_probe=tool_probe,
        runner_row=runner_row,
        materialized_rows=materialized_rows,
        previous_command_manifest=previous_command_manifest,
    )
    if not materialized_rows:
        blockers.append("no_raw_stage_outputs_materialized")
    status = "fresh_candidate_specific_execution_recorded" if not blockers else "blocked_fresh_candidate_specific_execution"
    return {
        "unit_id": f"{candidate_id}:{kernel_id}",
        "candidate_id": candidate_id,
        "kernel_id": kernel_id,
        "stage_ids": list(stage_ids),
        "status": status,
        "command_run_id": command_run_id,
        "unit_evidence_dir": str(unit_dir),
        "fresh_execution_work_dir": str(work_dir),
        "candidate_bundle_json": str(candidate_bundle_path),
        "removed_stale_files": removed,
        "tool_probe_status": tool_probe.get("probe_command", {}).get("status"),
        "runner_status": runner_row.get("status"),
        "runner_command": runner_row.get("command", []),
        "runner_returncode": runner_row.get("returncode"),
        "materialized_raw_file_count": len(materialized_rows),
        "materialized_rows": materialized_rows,
        "provenance_refs": provenance_refs,
        "blocker_ids": blockers,
        "hardware_completion_eligible": False,
        "deliverable_complete": False,
        "claim_boundary": _CLAIM_BOUNDARY,
    }


def build_dft_candidate_specific_ppa_execution(
    *,
    run_dir: Path,
    tie_breaker_queue_path: Path | None = None,
    candidate_ids: Sequence[str] = (),
    kernel_ids: Sequence[str] = (),
    stage_ids: Sequence[str] = (),
    max_units: int | None = None,
    ssh_target: str = "ic-eda",
    remote_base_dir: str = "/tmp",
    timeout_s: int = 900,
    skip_remote: bool = False,
    allow_blocked: bool = True,
) -> Dict[str, Any]:
    """Execute selected queue units and write fresh raw/provenance files."""

    run_dir = Path(run_dir)
    queue_path = Path(tie_breaker_queue_path or run_dir / "dft_hardware_tie_breaker_execution_queue.json")
    work_items = _queue_work_items(queue_path)
    selected = _selected_units(
        work_items,
        candidate_ids=candidate_ids,
        kernel_ids=kernel_ids,
        stage_ids=stage_ids,
        max_units=max_units,
    )
    shared_tool_probe = (
        _probe_tool_versions(ssh_target=ssh_target, timeout_s=timeout_s)
        if selected
        else None
    )
    unit_rows = [
        _run_unit(
            run_dir=run_dir,
            queue_unit=unit,
            ssh_target=ssh_target,
            remote_base_dir=remote_base_dir,
            timeout_s=timeout_s,
            skip_remote=skip_remote,
            allow_blocked=allow_blocked,
            tool_probe=shared_tool_probe,
        )
        for unit in selected
    ]
    blocked_count = sum(1 for row in unit_rows if str(row.get("status", "")).startswith("blocked"))
    status = (
        "failed_missing_tie_breaker_queue"
        if not queue_path.exists()
        else "failed_no_units_selected"
        if not selected
        else "fresh_candidate_specific_execution_recorded"
        if blocked_count == 0
        else "blocked_partial_fresh_candidate_specific_execution"
        if blocked_count < len(unit_rows)
        else "blocked_fresh_candidate_specific_execution"
    )
    return {
        "schema_version": DFT_CANDIDATE_SPECIFIC_PPA_EXECUTION_SCHEMA,
        "generated_at": _now_iso(),
        "status": status,
        "source_artifacts": {
            "tie_breaker_queue": _source_ref(queue_path, required=True),
        },
        "ssh_target": ssh_target,
        "remote_base_dir": remote_base_dir,
        "timeout_s": timeout_s,
        "skip_remote": skip_remote,
        "allow_blocked": allow_blocked,
        "selected_unit_count": len(selected),
        "executed_unit_count": len(unit_rows),
        "blocked_unit_count": blocked_count,
        "materialized_raw_file_count": sum(int(row.get("materialized_raw_file_count", 0) or 0) for row in unit_rows),
        "units": unit_rows,
        "hardware_completion_eligible": False,
        "deliverable_complete": False,
        "claim_boundary": _CLAIM_BOUNDARY,
    }


def validate_dft_candidate_specific_ppa_execution(payload_or_path: Mapping[str, Any] | Path) -> Dict[str, Any]:
    payload = _load_json(payload_or_path) if isinstance(payload_or_path, Path) else dict(payload_or_path)
    errors: list[Dict[str, Any]] = []
    if payload.get("schema_version") != DFT_CANDIDATE_SPECIFIC_PPA_EXECUTION_SCHEMA:
        errors.append({"field": "schema_version", "message": "unexpected candidate-specific PPA execution schema"})
    for field in ("hardware_completion_eligible", "deliverable_complete"):
        if payload.get(field) is True:
            errors.append({"field": field, "message": "fresh PPA execution cannot upgrade claims"})
    units = payload.get("units", [])
    if not isinstance(units, list):
        errors.append({"field": "units", "message": "units must be a list"})
        units = []
    if int(payload.get("executed_unit_count", 0) or 0) != len(units):
        errors.append({"field": "executed_unit_count", "message": "must match unit rows"})
    blocked_count = 0
    materialized_count = 0
    for index, row in enumerate(units):
        if not isinstance(row, Mapping):
            errors.append({"field": f"units[{index}]", "message": "unit row must be an object"})
            continue
        if str(row.get("status", "")).startswith("blocked"):
            blocked_count += 1
            if not row.get("blocker_ids"):
                errors.append({"field": f"units[{index}].blocker_ids", "message": "blocked unit requires blockers"})
        for field in ("hardware_completion_eligible", "deliverable_complete"):
            if row.get(field) is True:
                errors.append({"field": f"units[{index}].{field}", "message": "unit cannot upgrade claims"})
        materialized_count += int(row.get("materialized_raw_file_count", 0) or 0)
    if blocked_count != int(payload.get("blocked_unit_count", 0) or 0):
        errors.append({"field": "blocked_unit_count", "message": "must match unit rows"})
    if materialized_count != int(payload.get("materialized_raw_file_count", 0) or 0):
        errors.append({"field": "materialized_raw_file_count", "message": "must match unit rows"})
    return {
        "schema_version": DFT_CANDIDATE_SPECIFIC_PPA_EXECUTION_VALIDATION_SCHEMA,
        "valid": not errors,
        "executed_unit_count": len(units),
        "blocked_unit_count": blocked_count,
        "errors": errors,
        "claim_boundary": _CLAIM_BOUNDARY,
    }


def write_dft_candidate_specific_ppa_execution(
    out_dir: Path,
    *,
    run_dir: Path,
    tie_breaker_queue_path: Path | None = None,
    candidate_ids: Sequence[str] = (),
    kernel_ids: Sequence[str] = (),
    stage_ids: Sequence[str] = (),
    max_units: int | None = None,
    ssh_target: str = "ic-eda",
    remote_base_dir: str = "/tmp",
    timeout_s: int = 900,
    skip_remote: bool = False,
    allow_blocked: bool = True,
) -> Dict[str, Any]:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    payload = build_dft_candidate_specific_ppa_execution(
        run_dir=run_dir,
        tie_breaker_queue_path=tie_breaker_queue_path,
        candidate_ids=candidate_ids,
        kernel_ids=kernel_ids,
        stage_ids=stage_ids,
        max_units=max_units,
        ssh_target=ssh_target,
        remote_base_dir=remote_base_dir,
        timeout_s=timeout_s,
        skip_remote=skip_remote,
        allow_blocked=allow_blocked,
    )
    write_json(out_dir / "dft_candidate_specific_ppa_execution.json", payload)
    validation = validate_dft_candidate_specific_ppa_execution(payload)
    write_json(out_dir / "dft_candidate_specific_ppa_execution_validation.json", validation)
    status = {
        "schema_version": DFT_CANDIDATE_SPECIFIC_PPA_EXECUTION_STATUS_SCHEMA,
        "generated_at": _now_iso(),
        "status": "passed" if validation["valid"] else "failed",
        "execution_status": payload.get("status"),
        "execution": "dft_candidate_specific_ppa_execution.json",
        "validation": "dft_candidate_specific_ppa_execution_validation.json",
        "selected_unit_count": payload.get("selected_unit_count"),
        "executed_unit_count": payload.get("executed_unit_count"),
        "blocked_unit_count": payload.get("blocked_unit_count"),
        "materialized_raw_file_count": payload.get("materialized_raw_file_count"),
        "hardware_completion_eligible": False,
        "deliverable_complete": False,
        "claim_boundary": _CLAIM_BOUNDARY,
    }
    write_json(out_dir / "dft_candidate_specific_ppa_execution_status.json", status)
    return status


def build_dft_candidate_specific_ppa_execution_aggregate(
    run_dir: Path,
    *,
    shard_glob: str = "fresh_candidate_specific_ppa_execution_*/dft_candidate_specific_ppa_execution.json",
) -> Dict[str, Any]:
    """Aggregate per-batch fresh execution shards into the Step5 run root."""

    run_dir = Path(run_dir)
    shard_paths = sorted(
        path
        for path in run_dir.glob(shard_glob)
        if path.is_file()
        and path.parent != run_dir
        and path.resolve() != (run_dir / "dft_candidate_specific_ppa_execution.json").resolve()
    )
    units: list[Dict[str, Any]] = []
    source_refs: Dict[str, Any] = {}
    generated_at_values: list[str] = []
    for path in shard_paths:
        payload = _load_json(path)
        if not payload:
            continue
        generated_at = str(payload.get("generated_at") or "")
        if generated_at:
            generated_at_values.append(generated_at)
        try:
            rel = str(path.resolve().relative_to(run_dir.resolve()))
        except ValueError:
            rel = str(path)
        source_refs[path.parent.name] = {
            "path": rel,
            "exists": True,
            "sha256": sha256_file(path),
            "hash_algorithm": "sha256",
        }
        for unit in payload.get("units", []) or []:
            if isinstance(unit, Mapping):
                units.append(dict(unit))

    # De-duplicate rerun units by candidate/kernel, preserving the latest shard
    # in lexical path order.  Fresh reruns should supersede earlier blocked or
    # stale attempts for the same unit.
    by_unit: Dict[tuple[str, str], Dict[str, Any]] = {}
    for unit in units:
        by_unit[(str(unit.get("candidate_id")), str(unit.get("kernel_id")))] = unit
    deduped_units = sorted(
        by_unit.values(),
        key=lambda row: (str(row.get("candidate_id", "")), str(row.get("kernel_id", ""))),
    )
    blocked_count = sum(1 for unit in deduped_units if str(unit.get("status", "")).startswith("blocked"))
    status = (
        "fresh_candidate_specific_execution_recorded"
        if deduped_units and blocked_count == 0
        else "blocked_partial_fresh_candidate_specific_execution"
        if deduped_units
        else "no_fresh_candidate_specific_execution_shards"
    )
    return {
        "schema_version": DFT_CANDIDATE_SPECIFIC_PPA_EXECUTION_SCHEMA,
        "generated_at": max(generated_at_values) if generated_at_values else _now_iso(),
        "status": status,
        "source_artifacts": {"execution_shards": source_refs},
        "ssh_target": "mixed_or_recorded_per_unit",
        "timeout_s": "mixed_or_recorded_per_unit",
        "skip_remote": False,
        "allow_blocked": True,
        "selected_unit_count": len(deduped_units),
        "executed_unit_count": len(deduped_units),
        "blocked_unit_count": blocked_count,
        "materialized_raw_file_count": sum(int(unit.get("materialized_raw_file_count", 0) or 0) for unit in deduped_units),
        "units": deduped_units,
        "hardware_completion_eligible": False,
        "deliverable_complete": False,
        "claim_boundary": (
            "Aggregate of fresh candidate-specific PPA execution shard artifacts "
            "for reporting. It records command/tool provenance and raw evidence "
            "attempts only; parser/release/winner gates remain separate."
        ),
    }


def write_dft_candidate_specific_ppa_execution_aggregate(
    run_dir: Path,
    *,
    shard_glob: str = "fresh_candidate_specific_ppa_execution_*/dft_candidate_specific_ppa_execution.json",
) -> Dict[str, Any]:
    """Write root-level aggregate fresh execution artifacts for a Step5 run."""

    run_dir = Path(run_dir)
    payload = build_dft_candidate_specific_ppa_execution_aggregate(
        run_dir,
        shard_glob=shard_glob,
    )
    write_json(run_dir / "dft_candidate_specific_ppa_execution.json", payload)
    validation = validate_dft_candidate_specific_ppa_execution(payload)
    write_json(run_dir / "dft_candidate_specific_ppa_execution_validation.json", validation)
    status = {
        "schema_version": DFT_CANDIDATE_SPECIFIC_PPA_EXECUTION_STATUS_SCHEMA,
        "generated_at": payload.get("generated_at"),
        "status": "passed" if validation["valid"] else "failed",
        "execution_status": payload.get("status"),
        "execution": "dft_candidate_specific_ppa_execution.json",
        "validation": "dft_candidate_specific_ppa_execution_validation.json",
        "selected_unit_count": payload.get("selected_unit_count"),
        "executed_unit_count": payload.get("executed_unit_count"),
        "blocked_unit_count": payload.get("blocked_unit_count"),
        "materialized_raw_file_count": payload.get("materialized_raw_file_count"),
        "hardware_completion_eligible": False,
        "deliverable_complete": False,
        "claim_boundary": payload.get("claim_boundary", _CLAIM_BOUNDARY),
    }
    write_json(run_dir / "dft_candidate_specific_ppa_execution_status.json", status)
    return status


__all__ = [
    "DFT_CANDIDATE_SPECIFIC_PPA_EXECUTION_SCHEMA",
    "DFT_CANDIDATE_SPECIFIC_PPA_EXECUTION_STATUS_SCHEMA",
    "DFT_CANDIDATE_SPECIFIC_PPA_EXECUTION_VALIDATION_SCHEMA",
    "build_dft_candidate_specific_ppa_execution",
    "build_dft_candidate_specific_ppa_execution_aggregate",
    "materialize_fresh_candidate_specific_outputs",
    "validate_dft_candidate_specific_ppa_execution",
    "write_dft_candidate_specific_ppa_execution_aggregate",
    "write_dft_candidate_specific_ppa_execution",
]
