"""Reporting and claim-validation utilities for generic DSE runs."""

from dse_v2.reporting.final_report import (
    CLAIM_REQUIREMENTS,
    build_evidence_index,
    evidence_requirement_table,
    generate_final_report,
    generate_final_report_artifacts,
    render_markdown_report,
    validate_claim,
    validate_claims,
    validate_report_claims,
    write_final_report_artifacts,
)
from dse_v2.reporting.complete_dse_claims import (
    ANTI_DOWNGRADE_RULES,
    CLAIM_LABELS,
    REQUIRED_COMPLETE_DSE_REPORT_ARTIFACTS,
    ROW_REQUIRED_GATES,
    blocked_l4_row,
    build_coverage_claim_report,
    render_coverage_claim_markdown,
    render_prompt_to_artifact_markdown,
    trusted_l4_row,
    validate_complete_dse_claim_report,
    validate_l4_evidence_matrix_claims,
    write_complete_dse_reporting_package,
)

__all__ = [
    "ANTI_DOWNGRADE_RULES",
    "CLAIM_REQUIREMENTS",
    "CLAIM_LABELS",
    "REQUIRED_COMPLETE_DSE_REPORT_ARTIFACTS",
    "ROW_REQUIRED_GATES",
    "blocked_l4_row",
    "build_evidence_index",
    "build_coverage_claim_report",
    "evidence_requirement_table",
    "generate_final_report",
    "generate_final_report_artifacts",
    "render_coverage_claim_markdown",
    "render_markdown_report",
    "render_prompt_to_artifact_markdown",
    "trusted_l4_row",
    "validate_claim",
    "validate_claims",
    "validate_complete_dse_claim_report",
    "validate_l4_evidence_matrix_claims",
    "validate_report_claims",
    "write_complete_dse_reporting_package",
    "write_final_report_artifacts",
]
