from __future__ import annotations

from typing import Any, Mapping, Protocol, Sequence


class WorkloadAdapter(Protocol):
    name: str
    def detect(self, payload: Mapping[str, Any]) -> bool: ...
    def identity(self, payload: Mapping[str, Any]) -> dict[str, Any]: ...
    def domain_extension(self, payload: Mapping[str, Any]) -> dict[str, Any]: ...
    def workload_anchor_refs(self, payload: Mapping[str, Any]) -> dict[str, Any]: ...
    def application_graph(self, payload: Mapping[str, Any]) -> dict[str, Any]: ...
    def correctness_contract(self, payload: Mapping[str, Any]) -> dict[str, Any]: ...
    def legacy_aliases(self, payload: Mapping[str, Any]) -> dict[str, Any]: ...


class ArchitectureTemplateProvider(Protocol):
    def build_template(self, design_point: Mapping[str, Any], target_class: str) -> dict[str, Any]: ...


class TargetRealizer(Protocol):
    def realize(self, template: Mapping[str, Any], mapping: Mapping[str, Any]) -> dict[str, Any]: ...


class SearchBackend(Protocol):
    name: str
    def search(self, axes: Mapping[str, Sequence[Any]], limit: int) -> dict[str, Any]: ...


class FastModelBackend(Protocol):
    def evaluate(self, workload: Any, design_point: Any) -> Any: ...


class MultiFidelityScheduler(Protocol):
    def build_plan(self, rows: Sequence[Mapping[str, Any]]) -> dict[str, Any]: ...


class EvidenceAdapter(Protocol):
    def normalize(self, payload: Mapping[str, Any]) -> list[dict[str, Any]]: ...


class CalibrationEngine(Protocol):
    def fit(self, rows: Sequence[Mapping[str, Any]], evidence_rows: Sequence[Mapping[str, Any]]) -> dict[str, Any]: ...


class Adjudicator(Protocol):
    def summarize(self, rows: Sequence[Mapping[str, Any]]) -> dict[str, Any]: ...
